[colors]
    draw_bold_text_with_bright_colors = true
    [colors.primary]
        # background = "0x1a1b26"
        # foreground = "0xa9b1d6"
    [colors.normal]
        black   = "#1A1A1A"
        red     = "#F4005F"
        green   = "#98E024"
        yellow  = "#FA8419"
        blue    = "#9D65FF"
        magenta = "#F4005F"
        cyan    = "#58D1EB"
        white   = "#C4C5B5"
    [colors.bright]
        black   = "#625E4C"
        red     = "#F4005F"
        green   = "#98E024"
        yellow  = "#E0D561"
        blue    = "#9D65FF"
        magenta = "#F4005F"
        cyan    = "#58D1EB"
        white   = "#F6F6EF"

[env]
    TERM = "xterm-256color"
    COLORTERM = "truecolor"
    EDITOR = "nvim"

[font]
    size = 18
    [font.normal]
        family = "SourceCodePro"
        style  = "Bold Italic"
    [font.bold]
        family = "SourceCodePro"
        style  = "Bold Italic"
    [font.bold_italic]
        family = "SourceCodePro"
        style  = "Bold Italic"
    [font.glyph_offset]
        x = 0
        y = 0
    [font.offset]
        x = 0
        y = 0

[scrolling]
    history    = 10000
    multiplier = 4

[selection]
    save_to_clipboard     = true
    semantic_escape_chars = ",â”‚`|:\"' ()[]{}<>"

[terminal.shell]
    args    = ["-l", "-c", "tmux attach-session &> /dev/null || tmux new-session -s Dev &> /dev/null"]
    program = "/bin/zsh"

[window.dimensions]
    columns = 120
    lines   = 32

[window.padding]
    x = 1
    y = 1

[[keyboard.bindings]]
    action = "Quit"
    key    = "W"
    mods   = "Command|Shift"
[[keyboard.bindings]]
    action = "SpawnNewInstance"
    key    = "N"
    mods   = "Command"
[[keyboard.bindings]]
    chars = "\u001Bb"
    key   = "Left"
    mods  = "Alt"
[[keyboard.bindings]]
    chars = "\u001Bf"
    key   = "Right"
    mods  = "Alt"

[[keyboard.bindings]]
    chars = "\u0001"
    key   = "Left"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u0005"
    key   = "Right"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u0015"
    key   = "Back"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001B\u007F"
    key   = "Back"
    mods  = "Alt"

[[keyboard.bindings]]
    chars = "\u001cc"
    key   = "T"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001C&"
    key   = "W"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001Cp"
    key   = "LBracket"
    mods  = "Command|Shift"
[[keyboard.bindings]]
    chars = "\u001Cn"
    key   = "RBracket"
    mods  = "Command|Shift"
[[keyboard.bindings]]
    chars = "\u001C1"
    key   = "Key1"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001C2"
    key   = "Key2"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001C3"
    key   = "Key3"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001C4"
    key   = "Key4"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001C5"
    key   = "Key5"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001C6"
    key   = "Key6"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001C7"
    key   = "Key7"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001C8"
    key   = "Key8"
    mods  = "Command"
[[keyboard.bindings]]
    chars = "\u001C9"
    key   = "Key9"
    mods  = "Command"
[[keyboard.bindings]]
    action = "ReceiveChar"
    key    = "Back"

